using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CRUD.Models.CrudBD
{
    public class CountryModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Asegura que la columna id sea autoincremental
        [Column("id_codigo_pais")]
        public int IdCodigoPais { get; set; }
        [Column("nombre_pais")]
        public string NombrePais { get; set; } = string.Empty;
        [Column("codigo_marcacion")]
        public string CodigoMarcacion { get; set; } = string.Empty;

        // Declaro un diccionario, para no realizar consultas innesarias en BD
        public Dictionary<string, List<(string, string)>> Countries { get; set; }

        public CountryModel()
        {
            Countries = new Dictionary<string, List<(string, string)>>()
            {
                { "AF", [ ("Afganistán", "+93")] },
                { "AL", [ ("Albania", "+355") ] },
                { "DZ", [ ("Argelia", "+213") ]},
                { "AD", [ ("Andorra", "+376") ] },
                { "AO", [ ("Angola", "+244") ] },
                { "AG", [ ("Antigua y Barbuda", "+1-268") ] },
                { "AR", [ ("Argentina", "+54")] },
                { "AM", [ ("Armenia", "+374") ] },
                { "AU", [ ("Australia", "+61") ] },
                { "AT", [ ("Austria", "+43") ] },
                { "AZ", [ ("Azerbaiyán", "+994") ]},
                { "BS", [ ("Bahamas", "+1-242") ] },
                { "BH", [ ("Baréin", "+973") ] },
                { "BD", [ ("Bangladés", "+880") ] },
                { "BB", [ ("Barbados", "+1-246") ] },
                { "BY", [ ("Bielorrusia", "+375") ] },
                { "BE", [ ("Bélgica", "+32") ] },
                { "BZ", [ ("Belice", "+501") ] },
                { "BJ", [ ("Benín", "+229") ] },
                { "BT", [ ("Bután", "+975") ] },
                { "BO", [ ("Bolivia", "+591") ] },
                { "BA", [ ("Bosnia y Herzegovina", "+387")] },
                { "BW", [ ("Botswana", "+267") ] },
                { "BR", [ ("Brasil", "+55") ] },
                { "BN", [ ("Brunéi", "+673") ] },
                { "BG", [ ("Bulgaria", "+359") ] },
                { "BF", [ ("Burkina Faso", "+226") ] },
                { "BI", [ ("Burundi", "+257") ] },
                { "CV", [ ("Cabo Verde", "+238") ] },
                { "KH", [ ("Camboya", "+855") ] },
                { "CM", [ ("Camerún", "+237") ] },
                { "CA", [ ("Canadá", "+1") ] },
                { "CF", [ ("República Centroafricana", "+236") ] },
                { "TD", [ ("Chad", "+235") ] },
                { "CL", [ ("Chile", "+56") ] },
                { "CN", [ ("China", "+86") ] },
                { "CO", [ ("Colombia", "+57") ] },
                { "KM", [ ("Comoras", "+269") ] },
                { "CG", [ ("Congo", "+242") ] },
                { "CD", [ ("República Democrática del Congo", "+243") ] },
                { "CR", [ ("Costa Rica", "+506") ] },
                { "CI", [ ("Costa de Marfil", "+225") ] },
                { "HR", [ ("Croacia", "+385") ] },
                { "CU", [ ("Cuba", "+53") ] },
                { "CY", [ ("Chipre", "+357") ] },
                { "CZ", [ ("República Checa", "+420") ] },
                { "DK", [ ("Dinamarca", "+45") ] },
                { "DJ", [ ("Yibuti", "+253") ] },
                { "DM", [ ("Dominica", "+1-767") ] },
                { "DO", [ ("República Dominicana", "+1-809") ] },
                { "EC", [ ("Ecuador", "+593") ] },
                { "EG", [ ("Egipto", "+20") ] },
                { "SV", [ ("El Salvador", "+503") ] },
                { "GQ", [ ("Guinea Ecuatorial", "+240") ] },
                { "ER", [ ("Eritrea", "+291") ] },
                { "EE", [ ("Estonia", "+372") ] },
                { "SZ", [ ("Esuatini", "+268") ] },
                { "ET", [ ("Etiopía", "+251") ] },
                { "FJ", [ ("Fiyi", "+679") ] },
                { "FI", [ ("Finlandia", "+358") ] },
                { "FR", [ ("Francia", "+33") ] },
                { "GA", [ ("Gabón", "+241") ] },
                { "GM", [ ("Gambia", "+220") ] },
                { "GE", [ ("Georgia", "+995") ] },
                { "DE", [ ("Alemania", "+49") ] },
                { "GH", [ ("Ghana", "+233") ] },
                { "GR", [ ("Grecia", "+30") ] },
                { "GD", [ ("Granada", "+1-473") ] },
                { "GT", [ ("Guatemala", "+502") ] },
                { "GN", [ ("Guinea", "+224") ] },
                { "GW", [ ("Guinea-Bisáu", "+245") ] },
                { "GY", [ ("Guyana", "+592") ] },
                { "HT", [ ("Haití", "+509") ] },
                { "HN", [ ("Honduras", "+504") ] },
                { "HU", [ ("Hungría", "+36") ] },
                { "IS", [ ("Islandia", "+354") ] },
                { "IN", [ ("India", "+91") ] },
                { "ID", [ ("Indonesia", "+62") ] },
                { "IR", [ ("Irán", "+98") ] },
                { "IQ", [ ("Irak", "+964") ] },
                { "IE", [ ("Irlanda", "+353") ] },
                { "IL", [ ("Israel", "+972") ] },
                { "IT", [ ("Italia", "+39") ] },
                { "JM", [ ("Jamaica", "+1-876") ] },
                { "JP", [ ("Japón", "+81") ] },
                { "JO", [ ("Jordania", "+962") ] },
                { "KZ", [ ("Kazajistán", "+7") ] },
                { "KE", [ ("Kenia", "+254") ] },
                { "KI", [ ("Kiribati", "+686") ] },
                { "KP", [ ("Corea del Norte", "+850") ] },
                { "KR", [ ("Corea del Sur", "+82") ] },
                { "KW", [ ("Kuwait", "+965") ] },
                { "KG", [ ("Kirguistán", "+996") ] },
                { "LA", [ ("Laos", "+856") ] },
                { "LV", [ ("Letonia", "+371") ] },
                { "LB", [ ("Líbano", "+961") ] },
                { "LS", [ ("Lesoto", "+266") ] },
                { "LR", [ ("Liberia", "+231") ] },
                { "LY", [ ("Libia", "+218") ] },
                { "LI", [ ("Liechtenstein", "+423") ] },
                { "LT", [ ("Lituania", "+370") ] },
                { "LU", [ ("Luxemburgo", "+352") ]},
                { "MO", [ ("Macao", "+853") ]},
                { "MK", [ ("Macedonia del Norte", "+389") ]},
                { "MG", [ ("Madagascar", "+261") ]},
                { "MW", [ ("Malawi", "+265") ]},
                { "MY", [ ("Malasia", "+60") ]},
                { "MV", [ ("Maldivas", "+960") ]},
                { "ML", [ ("Malí", "+223") ]},
                { "MT", [ ("Malta", "+356") ]},
                { "MH", [ ("Islas Marshall", "+692") ]},
                { "MR", [ ("Mauritania", "+222") ]},
                { "MU", [ ("Mauricio", "+230") ]},
                { "MX", [ ("México", "+52") ]},
                { "FM", [ ("Micronesia", "+691") ]},
                { "MD", [ ("Moldavia", "+373") ]},
                { "MC", [ ("Mónaco", "+377") ]},
                { "MN", [ ("Mongolia", "+976") ]},
                { "ME", [ ("Montenegro", "+382") ]},
                { "MA", [ ("Marruecos", "+212") ]},
                { "MZ", [ ("Mozambique", "+258") ]},
                { "MM", [ ("Birmania", "+95") ]},
                { "NA", [ ("Namibia", "+264") ]},
                { "NR", [ ("Nauru", "+674") ]},
                { "NP", [ ("Nepal", "+977") ]},
                { "NL", [ ("Países Bajos", "+31") ]},
                { "NZ", [ ("Nueva Zelanda", "+64") ]},
                { "NI", [ ("Nicaragua", "+505") ]},
                { "NE", [ ("Níger", "+227") ]},
                { "NG", [ ("Nigeria", "+234") ]},
                { "NU", [ ("Niue", "+683") ]},
                { "NF", [ ("Isla Norfolk", "+672") ]},
                { "MP", [ ("Islas Marianas del Norte", "+1-670") ]},
                { "NO", [ ("Noruega", "+47") ]},
                { "OM", [ ("Omán", "+968") ]},
                { "PK", [ ("Pakistán", "+92") ]},
                { "PW", [ ("Palaos", "+680") ]},
                { "PA", [ ("Panamá", "+507") ]},
                { "PG", [ ("Papúa Nueva Guinea", "+675") ]},
                { "PY", [ ("Paraguay", "+595") ]},
                { "PE", [ ("Perú", "+51") ]},
                { "PH", [ ("Filipinas", "+63") ]},
                { "PN", [ ("Islas Pitcairn", "+64") ]},
                { "PL", [ ("Polonia", "+48") ]},
                { "PT", [ ("Portugal", "+351") ]},
                { "PR", [ ("Puerto Rico", "+1-787") ]},
                { "QA", [ ("Catar", "+974") ]},
                { "RE", [ ("Reunión", "+262") ]},
                { "RO", [ ("Rumania", "+40") ]},
                { "RU", [ ("Rusia", "+7") ]},
                { "RW", [ ("Ruanda", "+250") ]},
                { "SH", [ ("Santa Elena", "+290") ]},
                { "LC", [ ("Santa Lucía", "+1-758") ]},
                { "PM", [ ("San Pedro y Miquelón", "+508") ]},
                { "VC", [ ("San Vicente y las Granadinas", "+1-784") ]},
                { "WS", [ ("Samoa", "+685") ]},
                { "SM", [ ("San Marino", "+378") ]},
                { "ST", [ ("Santo Tomé y Príncipe", "+239") ]},
                { "SA", [ ("Arabia Saudita", "+966") ]},
                { "SN", [ ("Senegal", "+221") ]},
                { "SC", [ ("Seychelles", "+248") ]},
                { "SL", [ ("Sierra Leona", "+232") ]},
                { "SG", [ ("Singapur", "+65") ]},
                { "SX", [ ("San Martín", "+1-721") ]},
                { "SK", [ ("Eslovaquia", "+421") ]},
                { "SI", [ ("Eslovenia", "+386") ]},
                { "SB", [ ("Islas Salomón", "+677") ]},
                { "SO", [ ("Somalia", "+252") ]},
                { "ZA", [ ("Sudáfrica", "+27") ]},
                { "GS", [ ("Georgia del Sur", "+500") ]},
                { "ES", [ ("España", "+34") ]},
                { "LK", [ ("Sri Lanka", "+94") ]},
                { "SD", [ ("Sudán", "+249") ]},
                { "SR", [ ("Surinam", "+597") ]},
                { "SE", [ ("Suecia", "+46") ]},
                { "CH", [ ("Suiza", "+41") ]},
                { "SY", [ ("Siria", "+963") ]},
                { "TW", [ ("Taiwán", "+886") ]},
                { "TJ", [ ("Tayikistán", "+992") ]},
                { "TZ", [ ("Tanzania", "+255") ]},
                { "TH", [ ("Tailandia", "+66") ]},
                { "TL", [ ("Timor Oriental", "+670") ]},
                { "TG", [ ("Togo", "+228") ]},
                { "TK", [ ("Tokelau", "+690") ]},
                { "TO", [ ("Tonga", "+676") ]},
                { "TT", [ ("Trinidad y Tobago", "+1-868") ]},
                { "TN", [ ("Túnez", "+216") ]},
                { "TR", [ ("Turquía", "+90") ]},
                { "TM", [ ("Turkmenistán", "+993") ]},
                { "TV", [ ("Tuvalu", "+688") ]},
                { "UG", [ ("Uganda", "+256") ]},
                { "UA", [ ("Ucrania", "+380") ]},
                { "AE", [ ("Emiratos Árabes Unidos", "+971") ]},
                { "GB", [ ("Reino Unido", "+44") ]},
                { "US", [ ("Estados Unidos", "+1") ]},
                { "UY", [ ("Uruguay", "+598") ]},
                { "UZ", [ ("Uzbekistán", "+998") ]},
                { "VU", [ ("Vanuatu", "+678") ]},
                { "VE", [ ("Venezuela", "+58") ]},
                { "VN", [ ("Vietnam", "+84") ]},
                { "WF", [ ("Wallis y Futuna", "+681") ]},
                { "EH", [ ("Sáhara Occidental", "+212") ]},
                { "YE", [ ("Yemen", "+967") ]},
                { "ZM", [ ("Zambia", "+260") ]},
                { "ZW", [ ("Zimbabue", "+263") ]}
            };
        }

    }
}
